# Generated by Django 5.1.4 on 2024-12-11 04:32

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(storage=core.storage.CustomStorage(), upload_to=''),
        ),
    ]
