# Generated by Django 5.1.4 on 2024-12-11 06:35

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_noticias_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='existing_image',
            field=models.FilePathField(blank=True, match='.*\\.(jpg|png|jpeg)$', null=True, path='C:\\Users\\ignac\\Escritorio\\Trabajos\\perfectibles\\frontend\\src\\assets'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=core.storage.CustomStorage(), upload_to=''),
        ),
    ]
