# Generated by Django 5.1.4 on 2025-04-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_noticias_existing_image_alter_noticias_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this noticia as the featured one (only one can be featured).'),
        ),
    ]
